

default: &default
  adapter: postgresql
  encoding: unicode

  pool: 5

development:
  <<: *default
  database: crowdsource_due_diligence_development

test:
  <<: *default
  database:

production:
  <<: *default
  database:
  username:
  password:
